### ISSUE TITLE
Jquery auto scroll failure

### ISSUE THREAD

**Issue by ksume** [SinemSemsioglu/ekin-portfolio#8]
After a period of scrolling and navigation use, the section autofocusing stops working.

![screen shot 2016-01-19 at 15 29 24](https://cloud.githubusercontent.com/assets/7487706/12419893/9ce5c01e-bec1-11e5-81e4-4f9462944562.png)

**Comment by SinemSemsioglu** [comment]
As discussed before, this problem was because the 0th section was not initiated and therefore the element couldn't be found by JQuery. Since the 0th element is implemented, this is no longer an issue.
